// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "jaruvat.see@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/accounts": {
            "get": {
                "description": "ดึงรายการบัญชีทั้งหมดที่ is_active=true",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "ดึงรายการ Account ที่ใช้งานอยู่",
                "responses": {
                    "200": {
                        "description": "FetchActiveAccounts successful \u003cbr\u003emessage: FetchActiveAccounts successfull",
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_pkg_response.JsonResponse-array_github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto_AccountResponse"
                        }
                    },
                    "499": {
                        "description": "Client Closed Request  \u003cbr\u003eerror_code: REQUEST_CANCELED \u003cbr\u003emessage: The request was canceled by the user",
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.ErrorResponseDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error \u003cbr\u003eerror_code: INTERNAL_SERVER_ERROR or INTERNAL_DATABASE_ERROR \u003cbr\u003emessage: Something went wrong, please try again later",
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.ErrorResponseDTO"
                        }
                    },
                    "504": {
                        "description": "Gateway Timeout \u003cbr\u003eerror_code: DATABASE_TIMEOUT \u003cbr\u003emessage: The database operation timed out, please try again",
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.ErrorResponseDTO"
                        }
                    }
                }
            },
            "post": {
                "description": "สร้างบัญชีใหม่ โดยต้องระบุชื่อและประเภทของบัญชี",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "สร้าง Account ใหม่",
                "parameters": [
                    {
                        "description": "ข้อมูลสำหรับสร้าง Account",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.CreateAccountInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "create account successfull",
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_pkg_response.JsonResponse-github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto_AccountResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request  \u003cbr\u003eerror_code: INVALID_INPUT_PARAMETERS \u003cbr\u003emessage: 1. Invalid JSON format.  2. Validation failed for the request data.",
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.ErrorResponseDTO"
                        }
                    },
                    "499": {
                        "description": "Client Closed Request  \u003cbr\u003eerror_code: REQUEST_CANCELED \u003cbr\u003emessage: The request was canceled by the user",
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.ErrorResponseDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error \u003cbr\u003eerror_code: INTERNAL_SERVER_ERROR or INTERNAL_DATABASE_ERROR \u003cbr\u003emessage: Something went wrong, please try again later",
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.ErrorResponseDTO"
                        }
                    },
                    "504": {
                        "description": "Gateway Timeout \u003cbr\u003eerror_code: DATABASE_TIMEOUT \u003cbr\u003emessage: The database operation timed out, please try again",
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.ErrorResponseDTO"
                        }
                    }
                }
            }
        },
        "/accounts/{id}": {
            "delete": {
                "description": "ปิดใช้งานบัญชี (soft delete) โดยต้องระบุ ID ของบัญชีที่ต้องการลบ",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "ลบ Account",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID ของ Account ที่ต้องการลบ",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "400": {
                        "description": "Bad Request \u003cbr\u003eerror_code: INVALID_INPUT_PARAMETERS \u003cbr\u003eMessage: Invalid ID format. The path parameter 'id' must be a positive integer.",
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.ErrorResponseDTO"
                        }
                    },
                    "499": {
                        "description": "Client Closed Request  \u003cbr\u003eerror_code: REQUEST_CANCELED \u003cbr\u003emessage: The request was canceled by the user",
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.ErrorResponseDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error \u003cbr\u003eerror_code: INTERNAL_SERVER_ERROR or INTERNAL_DATABASE_ERROR \u003cbr\u003emessage: Something went wrong, please try again later",
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.ErrorResponseDTO"
                        }
                    },
                    "504": {
                        "description": "Gateway Timeout \u003cbr\u003eerror_code: DATABASE_TIMEOUT \u003cbr\u003emessage: The database operation timed out, please try again",
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.ErrorResponseDTO"
                        }
                    }
                }
            },
            "patch": {
                "description": "อัปเดตข้อมูลบัญชี โดยต้องระบุ ID ของบัญชีที่ต้องการอัปเดต",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "อัปเดต Account",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID ของ Account ที่ต้องการอัปเดต",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "ข้อมูลสำหรับอัปเดต Account",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.UpdateAccountInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "update account successfull",
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_pkg_response.JsonResponse-github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto_AccountResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request  \u003cbr\u003eerror_code: INVALID_INPUT_PARAMETERS \u003cbr\u003emessage: 1. Invalid ID format (must be a positive integer) 2. Invalid JSON format 3. Validation failed for the request data",
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.ErrorResponseDTO"
                        }
                    },
                    "499": {
                        "description": "Client Closed Request  \u003cbr\u003eerror_code: REQUEST_CANCELED \u003cbr\u003emessage: The request was canceled by the user",
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.ErrorResponseDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error \u003cbr\u003eerror_code: INTERNAL_SERVER_ERROR or INTERNAL_DATABASE_ERROR \u003cbr\u003emessage: Something went wrong, please try again later",
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.ErrorResponseDTO"
                        }
                    },
                    "504": {
                        "description": "Gateway Timeout \u003cbr\u003eerror_code: DATABASE_TIMEOUT \u003cbr\u003emessage: The database operation timed out, please try again",
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.ErrorResponseDTO"
                        }
                    }
                }
            }
        },
        "/categories": {
            "get": {
                "description": "ดึงข้อมูล Category ตามประเภท โดยต้องระบุประเภทของ Category (income หรือ expense)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Category"
                ],
                "summary": "ดึงข้อมูล Category ตามประเภท",
                "parameters": [
                    {
                        "enum": [
                            "income",
                            "expense"
                        ],
                        "type": "string",
                        "default": "expense",
                        "description": "ประเภทของ Category",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "FetchCategoriesByType successful \u003cbr\u003emessage: FetchCategoriesByType successfull",
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_pkg_response.JsonResponse-array_github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto_CategoryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request \u003cbr\u003eerror_code: INVALID_INPUT_PARAMETERS \u003cbr\u003emessage: Invalid query parameter 'type'. Allowed values are 'expense' or 'income'.",
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.ErrorResponseDTO"
                        }
                    },
                    "499": {
                        "description": "Client Closed Request  \u003cbr\u003eerror_code: REQUEST_CANCELED \u003cbr\u003emessage: The request was canceled by the user",
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.ErrorResponseDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error \u003cbr\u003eerror_code: INTERNAL_SERVER_ERROR or INTERNAL_DATABASE_ERROR \u003cbr\u003emessage: Something went wrong, please try again later",
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.ErrorResponseDTO"
                        }
                    },
                    "504": {
                        "description": "Gateway Timeout \u003cbr\u003eerror_code: DATABASE_TIMEOUT \u003cbr\u003emessage: The database operation timed out, please try again",
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.ErrorResponseDTO"
                        }
                    }
                }
            },
            "post": {
                "description": "สร้าง Category ใหม่ โดยต้องระบุชื่อและประเภทของ Category",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Category"
                ],
                "summary": "สร้าง Category ใหม่",
                "parameters": [
                    {
                        "description": "ข้อมูลสำหรับสร้าง Category",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.CreateCategoryInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "create category successfull",
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_pkg_response.JsonResponse-github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto_CategoryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request  \u003cbr\u003eerror_code: INVALID_INPUT_PARAMETERS \u003cbr\u003emessage: 1. Invalid JSON format.  2. Validation failed for the request data.",
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.ErrorResponseDTO"
                        }
                    },
                    "499": {
                        "description": "Client Closed Request  \u003cbr\u003eerror_code: REQUEST_CANCELED \u003cbr\u003emessage: The request was canceled by the user",
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.ErrorResponseDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error \u003cbr\u003eerror_code: INTERNAL_SERVER_ERROR or INTERNAL_DATABASE_ERROR \u003cbr\u003emessage: Something went wrong, please try again later",
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.ErrorResponseDTO"
                        }
                    },
                    "504": {
                        "description": "Gateway Timeout \u003cbr\u003eerror_code: DATABASE_TIMEOUT \u003cbr\u003emessage: The database operation timed out, please try again",
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.ErrorResponseDTO"
                        }
                    }
                }
            }
        },
        "/categories/{id}": {
            "delete": {
                "description": "ลบ Category โดยต้องระบุ ID ของ Category ที่ต้องการลบ",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Category"
                ],
                "summary": "ลบ Category",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID ของ Category ที่ต้องการลบ",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "400": {
                        "description": "Bad Request \u003cbr\u003eerror_code: INVALID_INPUT_PARAMETERS \u003cbr\u003eMessage: Invalid ID format. The path parameter 'id' must be a positive integer.",
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.ErrorResponseDTO"
                        }
                    },
                    "499": {
                        "description": "Client Closed Request  \u003cbr\u003eerror_code: REQUEST_CANCELED \u003cbr\u003emessage: The request was canceled by the user",
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.ErrorResponseDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error \u003cbr\u003eerror_code: INTERNAL_SERVER_ERROR or INTERNAL_DATABASE_ERROR \u003cbr\u003emessage: Something went wrong, please try again later",
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.ErrorResponseDTO"
                        }
                    },
                    "504": {
                        "description": "Gateway Timeout \u003cbr\u003eerror_code: DATABASE_TIMEOUT \u003cbr\u003emessage: The database operation timed out, please try again",
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.ErrorResponseDTO"
                        }
                    }
                }
            },
            "patch": {
                "description": "อัปเดตข้อมูล Category โดยต้องระบุ ID ของ Category ที่ต้องการอัปเดต",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Category"
                ],
                "summary": "อัปเดต Category",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID ของ Category ที่ต้องการอัปเดต",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "ข้อมูลสำหรับอัปเดต Category",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.UpdateCategoryInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "update category successfull",
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_pkg_response.JsonResponse-github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto_CategoryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request  \u003cbr\u003eerror_code: INVALID_INPUT_PARAMETERS \u003cbr\u003emessage: 1. Invalid ID format (must be a positive integer) 2. Invalid JSON format 3. Validation failed for the request data",
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.ErrorResponseDTO"
                        }
                    },
                    "499": {
                        "description": "Client Closed Request  \u003cbr\u003eerror_code: REQUEST_CANCELED \u003cbr\u003emessage: The request was canceled by the user",
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.ErrorResponseDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error \u003cbr\u003eerror_code: INTERNAL_SERVER_ERROR or INTERNAL_DATABASE_ERROR \u003cbr\u003emessage: Something went wrong, please try again later",
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.ErrorResponseDTO"
                        }
                    },
                    "504": {
                        "description": "Gateway Timeout \u003cbr\u003eerror_code: DATABASE_TIMEOUT \u003cbr\u003emessage: The database operation timed out, please try again",
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.ErrorResponseDTO"
                        }
                    }
                }
            }
        },
        "/transactions": {
            "post": {
                "description": "สร้างธุรกรรม income หรือ expense ด้วยตนเอง โดยต้องระบุ account_id ที่ active อยู่",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transaction"
                ],
                "summary": "สร้างธุรกรรม income/expense แบบ manual",
                "parameters": [
                    {
                        "description": "ข้อมูลสำหรับสร้างธุรกรรม",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.CreateTransactionInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Transaction created successfully",
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_pkg_response.JsonResponse-github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto_TransactionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request  \u003cbr\u003eerror_code: INVALID_INPUT_PARAMETERS \u003cbr\u003emessage: 1. Invalid JSON format. 2. Validation failed for the request data.",
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.ErrorResponseDTO"
                        }
                    },
                    "499": {
                        "description": "Client Closed Request  \u003cbr\u003eerror_code: REQUEST_CANCELED \u003cbr\u003emessage: The request was canceled by the user",
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.ErrorResponseDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error \u003cbr\u003eerror_code: INTERNAL_SERVER_ERROR or INTERNAL_DATABASE_ERROR \u003cbr\u003emessage: Something went wrong, please try again later",
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.ErrorResponseDTO"
                        }
                    },
                    "504": {
                        "description": "Gateway Timeout \u003cbr\u003eerror_code: DATABASE_TIMEOUT \u003cbr\u003emessage: The database operation timed out, please try again",
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.ErrorResponseDTO"
                        }
                    }
                }
            }
        },
        "/transactions/": {
            "get": {
                "description": "ดึงข้อมูล Transaction ตามเวลาที่กำหนด โดยสามารถระบุปี เดือน และการแบ่งหน้า (Pagination) ได้ผ่าน Query Parameters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transaction"
                ],
                "summary": "ดึงข้อมูล Transaction ตามเวลาที่กำหนด",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ปีที่ต้องการดึงข้อมูล",
                        "name": "year",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "เดือนที่ต้องการดึงข้อมูล (1-12)",
                        "name": "month",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "หน้าที่ต้องการดึงข้อมูล",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "จำนวนรายการต่อหน้า",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ดึงข้อมูล Transaction สำเร็จ",
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_pkg_response.PaginatedResponse-github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto_TransactionResponse"
                        }
                    },
                    "499": {
                        "description": "Client Closed Request  \u003cbr\u003eerror_code: REQUEST_CANCELED \u003cbr\u003emessage: The request was canceled by the user",
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.ErrorResponseDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error \u003cbr\u003eerror_code: INTERNAL_SERVER_ERROR or INTERNAL_DATABASE_ERROR \u003cbr\u003emessage: Something went wrong, please try again later",
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.ErrorResponseDTO"
                        }
                    },
                    "504": {
                        "description": "Gateway Timeout \u003cbr\u003eerror_code: DATABASE_TIMEOUT \u003cbr\u003emessage: The database operation timed out, please try again",
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.ErrorResponseDTO"
                        }
                    }
                }
            }
        },
        "/transactions/summary": {
            "get": {
                "description": "ดึงข้อมูลสรุปรายรับ-รายจ่ายประจำเดือนหรือรายปี โดยสามารถระบุช่วงเวลาได้ผ่าน Query Parameters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transaction"
                ],
                "summary": "ดึงข้อมูลสรุปรายรับ-รายจ่ายประจำเดือนหรือรายปี",
                "parameters": [
                    {
                        "enum": [
                            "monthly",
                            "yearly"
                        ],
                        "type": "string",
                        "default": "monthly",
                        "description": "ช่วงเวลาที่ต้องการดึงข้อมูล",
                        "name": "scope",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "เดือนที่ต้องการดึงข้อมูล (1-12)",
                        "name": "month",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "ปีที่ต้องการดึงข้อมูล",
                        "name": "year",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Dashboard summary fetched successfully",
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_pkg_response.JsonResponse-github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto_DashboardSummaryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request  \u003cbr\u003eerror_code: INVALID_INPUT_PARAMETERS \u003cbr\u003emessage: Invalid query parameter 'scope'. Allowed values are 'monthly' or 'yearly'.",
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.ErrorResponseDTO"
                        }
                    },
                    "499": {
                        "description": "Client Closed Request  \u003cbr\u003eerror_code: REQUEST_CANCELED \u003cbr\u003emessage: The request was canceled by the user",
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.ErrorResponseDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error \u003cbr\u003eerror_code: INTERNAL_SERVER_ERROR or INTERNAL_DATABASE_ERROR \u003cbr\u003emessage: Something went wrong, please try again later",
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.ErrorResponseDTO"
                        }
                    },
                    "504": {
                        "description": "Gateway Timeout \u003cbr\u003eerror_code: DATABASE_TIMEOUT \u003cbr\u003emessage: The database operation timed out, please try again",
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.ErrorResponseDTO"
                        }
                    }
                }
            }
        },
        "/transactions/transfer": {
            "post": {
                "description": "สร้างธุรกรรม transfer ระหว่าง 2 บัญชีด้วยตนเอง โดย from_account_id ต้องไม่เท่ากับ to_account_id และทั้งคู่ต้อง active อยู่",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transaction"
                ],
                "summary": "สร้างธุรกรรม transfer แบบ manual",
                "parameters": [
                    {
                        "description": "ข้อมูลสำหรับสร้างธุรกรรม transfer",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.CreateTransferInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Transfer created successfully",
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_pkg_response.JsonResponse-github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto_TransactionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request  \u003cbr\u003eerror_code: INVALID_INPUT_PARAMETERS \u003cbr\u003emessage: 1. Invalid JSON format. 2. Validation failed for the request data. 3. from_account_id เท่ากับ to_account_id. 4. category_id ถูกส่งมาสำหรับ transfer",
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.ErrorResponseDTO"
                        }
                    },
                    "499": {
                        "description": "Client Closed Request  \u003cbr\u003eerror_code: REQUEST_CANCELED \u003cbr\u003emessage: The request was canceled by the user",
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.ErrorResponseDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error \u003cbr\u003eerror_code: INTERNAL_SERVER_ERROR or INTERNAL_DATABASE_ERROR \u003cbr\u003emessage: Something went wrong, please try again later",
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.ErrorResponseDTO"
                        }
                    },
                    "504": {
                        "description": "Gateway Timeout \u003cbr\u003eerror_code: DATABASE_TIMEOUT \u003cbr\u003emessage: The database operation timed out, please try again",
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.ErrorResponseDTO"
                        }
                    }
                }
            }
        },
        "/transactions/upload-slip": {
            "post": {
                "description": "อัปโหลดสลิปและบันทึก Transaction โดยต้องแนบไฟล์สลิปและระบุชื่อไฟล์ต้นฉบับ",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transaction"
                ],
                "summary": "อัปโหลดสลิปและบันทึก Transaction",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ชื่อไฟล์ต้นฉบับของสลิป",
                        "name": "local_image_name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "ไฟล์สลิป (รูปภาพ)",
                        "name": "image",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Transaction processed successfully",
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_pkg_response.JsonResponse-github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto_CategoryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request  \u003cbr\u003eerror_code: INVALID_INPUT_PARAMETERS \u003cbr\u003emessage: 1. Missing required form field 'local_image_name' 2. Missing required file 'image' in multipart/form-data request.",
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.ErrorResponseDTO"
                        }
                    },
                    "499": {
                        "description": "Client Closed Request  \u003cbr\u003eerror_code: REQUEST_CANCELED \u003cbr\u003emessage: The request was canceled by the user",
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.ErrorResponseDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error \u003cbr\u003eerror_code: INTERNAL_SERVER_ERROR or INTERNAL_DATABASE_ERROR \u003cbr\u003emessage: Something went wrong, please try again later",
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.ErrorResponseDTO"
                        }
                    },
                    "504": {
                        "description": "Gateway Timeout \u003cbr\u003eerror_code: DATABASE_TIMEOUT \u003cbr\u003emessage: The database operation timed out, please try again",
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.ErrorResponseDTO"
                        }
                    }
                }
            }
        },
        "/transactions/{id}": {
            "delete": {
                "description": "ลบข้อมูล Transaction โดยต้องระบุ ID ของ Transaction ที่ต้องการลบ",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transaction"
                ],
                "summary": "ลบข้อมูล Transaction",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID ของ Transaction ที่ต้องการลบ",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Transaction deleted successfully",
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_pkg_response.JsonResponse-github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto_EmptyData"
                        }
                    },
                    "400": {
                        "description": "Bad Request  \u003cbr\u003eerror_code: INVALID_INPUT_PARAMETERS \u003cbr\u003emessage: 1. Invalid ID format. The path parameter 'id' must be a positive integer.",
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.ErrorResponseDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error \u003cbr\u003eerror_code: INTERNAL_SERVER_ERROR or INTERNAL_DATABASE_ERROR \u003cbr\u003emessage: Something went wrong, please try again later",
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.ErrorResponseDTO"
                        }
                    },
                    "504": {
                        "description": "Gateway Timeout \u003cbr\u003eerror_code: DATABASE_TIMEOUT \u003cbr\u003emessage: The database operation timed out, please try again",
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.ErrorResponseDTO"
                        }
                    }
                }
            },
            "patch": {
                "description": "แก้ไขข้อมูล Transaction โดยต้องระบุ ID ของ Transaction ที่ต้องการแก้ไข และสามารถแก้ไขข้อมูลบางส่วนได้ (Partial Update)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transaction"
                ],
                "summary": "แก้ไขข้อมูล Transaction",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID ของ Transaction ที่ต้องการแก้ไข",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "ข้อมูลที่ต้องการแก้ไข (Partial Update)",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.UpdateTransactionInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Transaction updated successfully",
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_pkg_response.JsonResponse-github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto_TransactionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request  \u003cbr\u003eerror_code: INVALID_INPUT_PARAMETERS \u003cbr\u003emessage: 1. Invalid ID format. The path parameter 'id' must be a positive integer. 2. Invalid JSON format. 3. Validation failed for the request data",
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.ErrorResponseDTO"
                        }
                    },
                    "499": {
                        "description": "Client Closed Request  \u003cbr\u003eerror_code: REQUEST_CANCELED \u003cbr\u003emessage: The request was canceled by the user",
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.ErrorResponseDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error \u003cbr\u003eerror_code: INTERNAL_SERVER_ERROR or INTERNAL_DATABASE_ERROR \u003cbr\u003emessage: Something went wrong, please try again later",
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.ErrorResponseDTO"
                        }
                    },
                    "504": {
                        "description": "Gateway Timeout \u003cbr\u003eerror_code: DATABASE_TIMEOUT \u003cbr\u003emessage: The database operation timed out, please try again",
                        "schema": {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.ErrorResponseDTO"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.AccountResponse": {
            "type": "object",
            "properties": {
                "account_type": {
                    "type": "string",
                    "example": "bank"
                },
                "color_hex": {
                    "type": "string",
                    "example": "#4F46E5"
                },
                "icon_key": {
                    "type": "string",
                    "example": "bank"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                },
                "matching_keywords": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "SCB"
                    ]
                },
                "name": {
                    "type": "string",
                    "example": "SCB"
                },
                "opening_balance": {
                    "type": "number",
                    "example": 1000
                }
            }
        },
        "github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.CategoryBreakdownDTO": {
            "type": "object",
            "properties": {
                "category_id": {
                    "type": "integer"
                },
                "category_name": {
                    "type": "string"
                },
                "color_hex": {
                    "description": "เก็บโค้ดสี เช่น \"#EF4444\"",
                    "type": "string"
                },
                "icon_key": {
                    "description": "เก็บชื่อกลาง เช่น \"utensils\", \"zap\", \"wallet\"",
                    "type": "string"
                },
                "total_amount": {
                    "type": "number"
                }
            }
        },
        "github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.CategoryResponse": {
            "type": "object",
            "properties": {
                "color_hex": {
                    "type": "string",
                    "example": "#FF0000"
                },
                "icon_key": {
                    "type": "string",
                    "example": "food"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "อาหาร"
                },
                "type": {
                    "type": "string",
                    "example": "expense"
                }
            }
        },
        "github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.CreateAccountInput": {
            "type": "object",
            "required": [
                "account_type",
                "matching_keywords",
                "name"
            ],
            "properties": {
                "account_type": {
                    "type": "string",
                    "enum": [
                        "cash",
                        "bank",
                        "investment",
                        "ewallet"
                    ],
                    "example": "bank"
                },
                "color_hex": {
                    "type": "string",
                    "maxLength": 10,
                    "example": "#4F46E5"
                },
                "icon_key": {
                    "type": "string",
                    "maxLength": 50,
                    "example": "bank"
                },
                "matching_keywords": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "SCB"
                    ]
                },
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1,
                    "example": "SCB"
                },
                "opening_balance": {
                    "type": "number",
                    "minimum": 0,
                    "example": 1000
                }
            }
        },
        "github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.CreateCategoryInput": {
            "type": "object",
            "required": [
                "name",
                "type"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 2,
                    "example": "อาหาร"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "income",
                        "expense"
                    ],
                    "example": "expense"
                }
            }
        },
        "github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.CreateTransactionInput": {
            "type": "object",
            "required": [
                "account_id",
                "amount",
                "transaction_type"
            ],
            "properties": {
                "account_id": {
                    "type": "integer",
                    "example": 1
                },
                "amount": {
                    "type": "number",
                    "example": 150.5
                },
                "category_id": {
                    "type": "integer",
                    "example": 2
                },
                "note": {
                    "type": "string",
                    "maxLength": 255,
                    "example": "ค่ากาแฟอเมริกาโน่เย็น"
                },
                "transaction_date": {
                    "type": "string",
                    "example": "2026-07-24T14:30:00+07:00"
                },
                "transaction_type": {
                    "type": "string",
                    "enum": [
                        "income",
                        "expense"
                    ],
                    "example": "expense"
                }
            }
        },
        "github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.CreateTransferInput": {
            "type": "object",
            "required": [
                "amount",
                "from_account_id",
                "to_account_id"
            ],
            "properties": {
                "amount": {
                    "type": "number",
                    "example": 150.5
                },
                "category_id": {
                    "type": "integer",
                    "example": 2
                },
                "from_account_id": {
                    "type": "integer",
                    "example": 1
                },
                "note": {
                    "type": "string",
                    "maxLength": 255,
                    "example": "โอนเงินไปบัญชีออมทรัพย์"
                },
                "to_account_id": {
                    "type": "integer",
                    "example": 2
                },
                "transaction_date": {
                    "type": "string",
                    "example": "2026-07-24T14:30:00+07:00"
                }
            }
        },
        "github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.DashboardSummaryResponse": {
            "type": "object",
            "properties": {
                "expense": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.CategoryBreakdownDTO"
                    }
                },
                "income": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.CategoryBreakdownDTO"
                    }
                },
                "month": {
                    "type": "integer"
                },
                "scope": {
                    "type": "string"
                },
                "total_expense": {
                    "type": "number"
                },
                "total_income": {
                    "type": "number"
                },
                "year": {
                    "type": "integer"
                }
            }
        },
        "github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.EmptyData": {
            "type": "object"
        },
        "github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.ErrorResponseDTO": {
            "type": "object",
            "properties": {
                "error_code": {
                    "type": "string",
                    "example": "ERROR_CODE_HERE"
                },
                "message": {
                    "type": "string",
                    "example": "ข้อความอธิบายความผิดพลาดตามสถานการณ์"
                },
                "success": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.TransactionCategoryInfo": {
            "type": "object",
            "properties": {
                "color_hex": {
                    "type": "string",
                    "example": "#EF4444"
                },
                "icon_key": {
                    "type": "string",
                    "example": "utensils"
                },
                "id": {
                    "type": "integer",
                    "example": 3
                },
                "name": {
                    "type": "string",
                    "example": "อาหารและเครื่องดื่ม"
                },
                "type": {
                    "type": "string",
                    "example": "expense"
                }
            }
        },
        "github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.TransactionResponse": {
            "type": "object",
            "properties": {
                "account_id": {
                    "type": "integer",
                    "example": 1
                },
                "amount": {
                    "type": "number",
                    "example": 350.5
                },
                "category": {
                    "description": "แนบข้อมูลหมวดหมู่ย่อยแบบ Nested Object",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.TransactionCategoryInfo"
                        }
                    ]
                },
                "from_account_id": {
                    "type": "integer",
                    "example": 1
                },
                "id": {
                    "type": "integer",
                    "example": 102
                },
                "local_image_name": {
                    "type": "string",
                    "example": "slip_20260714_xyz.jpg"
                },
                "note": {
                    "type": "string",
                    "example": "มื้อเที่ยงกับทีมงาน"
                },
                "receiver_name": {
                    "type": "string",
                    "example": "ร้านข้าวมันไก่ป้าใจ"
                },
                "sender_name": {
                    "type": "string",
                    "example": "นายเอ สมมติ"
                },
                "source": {
                    "type": "string",
                    "example": "slip"
                },
                "to_account_id": {
                    "type": "integer",
                    "example": 2
                },
                "transaction_date": {
                    "type": "string",
                    "example": "2026-07-14T12:30:00+07:00"
                },
                "transaction_type": {
                    "type": "string",
                    "example": "expense"
                }
            }
        },
        "github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.UpdateAccountInput": {
            "type": "object",
            "required": [
                "matching_keywords"
            ],
            "properties": {
                "account_type": {
                    "type": "string",
                    "enum": [
                        "cash",
                        "bank",
                        "investment",
                        "ewallet"
                    ],
                    "example": "bank"
                },
                "color_hex": {
                    "type": "string",
                    "maxLength": 10,
                    "example": "#4F46E5"
                },
                "icon_key": {
                    "type": "string",
                    "maxLength": 50,
                    "example": "bank"
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                },
                "matching_keywords": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "SCB"
                    ]
                },
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1,
                    "example": "SCB"
                }
            }
        },
        "github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.UpdateCategoryInput": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 3,
                    "example": "อาหาร"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "income",
                        "expense"
                    ],
                    "example": "expense"
                }
            }
        },
        "github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.UpdateTransactionInput": {
            "type": "object",
            "properties": {
                "account_id": {
                    "type": "integer",
                    "example": 1
                },
                "amount": {
                    "type": "number",
                    "example": 150.5
                },
                "category_id": {
                    "type": "integer",
                    "example": 2
                },
                "from_account_id": {
                    "type": "integer",
                    "example": 1
                },
                "note": {
                    "type": "string",
                    "maxLength": 255,
                    "example": "ค่ากาแฟอเมริกาโน่เย็น"
                },
                "to_account_id": {
                    "type": "integer",
                    "example": 2
                },
                "transaction_date": {
                    "type": "string",
                    "example": "2026-07-24T14:30:00+07:00"
                }
            }
        },
        "github_com_Jaruvat303_cashlog_pkg_response.JsonResponse-array_github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto_AccountResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.AccountResponse"
                    }
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "github_com_Jaruvat303_cashlog_pkg_response.JsonResponse-array_github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto_CategoryResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.CategoryResponse"
                    }
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "github_com_Jaruvat303_cashlog_pkg_response.JsonResponse-github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto_AccountResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.AccountResponse"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "github_com_Jaruvat303_cashlog_pkg_response.JsonResponse-github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto_CategoryResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.CategoryResponse"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "github_com_Jaruvat303_cashlog_pkg_response.JsonResponse-github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto_DashboardSummaryResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.DashboardSummaryResponse"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "github_com_Jaruvat303_cashlog_pkg_response.JsonResponse-github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto_EmptyData": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.EmptyData"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "github_com_Jaruvat303_cashlog_pkg_response.JsonResponse-github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto_TransactionResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.TransactionResponse"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "github_com_Jaruvat303_cashlog_pkg_response.PaginatedResponse-github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto_TransactionResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_Jaruvat303_cashlog_internal_delivery_http_v1_dto.TransactionResponse"
                    }
                },
                "message": {
                    "type": "string"
                },
                "meta": {
                    "$ref": "#/definitions/github_com_Jaruvat303_cashlog_pkg_response.PaginationMeta"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "github_com_Jaruvat303_cashlog_pkg_response.PaginationMeta": {
            "type": "object",
            "properties": {
                "current_page": {
                    "type": "integer",
                    "example": 1
                },
                "page_size": {
                    "type": "integer",
                    "example": 10
                },
                "total_items": {
                    "type": "integer",
                    "example": 100
                },
                "total_pages": {
                    "type": "integer",
                    "example": 10
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "CashLog API",
	Description:      "API บริการหลังบ้านสำหรับจัดการบันทึกรายรับรายจ่ายและวิเคราะห์สลิปด้วย Gemini AI",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
